# Generated by Django 4.0.2 on 2022-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertask',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='usertask',
            name='task',
            field=models.CharField(max_length=500),
        ),
    ]
